config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }
  
  root 'home#wellcome'

  resources :todo_lists do
    resources :todo_items do
    	member do
    		patch :complete
    	end	
    end	
  end  

end

app/models/todo_item.rb
class TodoItem < ActiveRecord::Base
	#Listando de menor a mayor
	default_scope { order(created_at: :desc) }	

	belongs_to :todo_list

	def completed?
 		!completed_at.blank?
	end

end

app/models/todo_list.rb
class TodoList < ActiveRecord::Base
	#that the existence of tasks is dependent on the existence of the todo lists
	has_many :todo_items, dependent: :destroy

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable

  def self.find_for_twitter_oauth(auth, signed_in_resource=nil)
    user = User.where(:provider => auth.provider, :uid => auth.uid).first
    if user
      return user
    else
      registered_user = User.where(:email => auth.uid + "@twitter.com").first
      if registered_user
        return registered_user
      else

        user = User.create(name:auth.extra.raw_info.name,
                            provider:auth.provider,
                            uid:auth.uid,
                            email:auth.uid+"@twitter.com",
                            password:Devise.friendly_token[0,20],
                          )
      end

    end
  end       
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def wellcome
  	if user_signed_in?
  		redirect_to todo_lists_url, notice: "Wellcome"
  	end	
  end
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController   
    def twitter
        auth = env["omniauth.auth"]

        @user = User.find_for_twitter_oauth(request.env["omniauth.auth"],current_user)
        if @user.persisted?
          flash[:notice] = I18n.t "devise.omniauth_callbacks.success"
          sign_in_and_redirect @user, :event => :authentication
        else
          session["devise.twitter_uid"] = request.env["omniauth.auth"]
          redirect_to new_user_registration_url
        end
    end
end      

app/controllers/todo_items_controller.rb
class TodoItemsController < ApplicationController
	before_action :set_todo_list
	before_action :set_todo_items, except: [:create]

	def create
		@todo_item = @todo_list.todo_items.create(todo_items_params)
		redirect_to @todo_list, notice: "New task created!"
	end

	def destroy
		if @todo_item.destroy
			#Forma corta
			redirect_to @todo_list, notice: "Task deleted"
		else
			#Forma larga
			redirect_to @todo_list
			flash[:error] = "Whoops we have a truoble"
		end		
	end

	def complete
		@todo_item.update_attribute(:completed_at, Time.now)
		redirect_to @todo_list, notice: "Taks completed !"
	end

	private

	def todo_items_params
		params[:todo_item].permit(:title, :total_time)
	end

	def set_todo_list
		@todo_list = TodoList.find(params[:todo_list_id])
	end

	def set_todo_items
		@todo_item = @todo_list.todo_items.find(params[:id])
	end
end

app/controllers/todo_lists_controller.rb
class TodoListsController < ApplicationController
  before_action :set_todo_list, only: [:show, :edit, :update, :destroy]

  def index
    @todo_list = TodoList.find_by_id(params[:id])
    @todo_lists = TodoList.all.order("created_at DESC")
  end

  def show
    @todo_lists = TodoList.all
    @todo_items = TodoItem.all
    #@todo_item = TodoItem.find(params[:id])
  end


  def new
    @todo_list = TodoList.new
  end


  def edit
  end


  def create
    @todo_list = TodoList.new(todo_list_params)

    respond_to do |format|
      if @todo_list.save
        format.html { redirect_to @todo_list, notice: 'Todo list was successfully created.' }
        format.json { render :show, status: :created, location: @todo_list }
      else
        format.html { render :new }
        format.json { render json: @todo_list.errors, status: :unprocessable_entity }
      end
    end
  end


  def update
    respond_to do |format|
      if @todo_list.update(todo_list_params)
        format.html { redirect_to @todo_list, notice: 'Todo list was successfully updated.' }
        format.json { render :show, status: :ok, location: @todo_list }
      else
        format.html { render :edit }
        format.json { render json: @todo_list.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @todo_list.destroy
    respond_to do |format|
      format.html { redirect_to todo_lists_url, notice: 'Todo list was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def set_todo_list
      @todo_list = TodoList.find(params[:id])
    end


    def todo_list_params
      params.require(:todo_list).permit(:title, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(type)
    case type
    when :success then "alert-success"
    when :error then "alert-danger"
    when :alert then "alert-danger"
    when :notice then "alert-success"
    else "alert-info"
    end 
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/todo_items_helper.rb
module TodoItemsHelper
=begin
	
	def giving_time(completed, created)
		completed = @todo_item.completed_at
		created_time = @todo_item.created_at
		diff_hours = ((complete_time - created_time) / 1.hour).round
		@hours = TimeDifference.between(complete_time, created_time).in_hours.to_i 
		@minutes = TimeDifference.between(complete_time, created_time).in_minutes.to_i 
		@seconds = TimeDifference.between(complete_time, created_time).in_seconds.to_i.round 
		@spent_time = [@hours, @minutes, @seconds].join(':')	
	end

=end
end

app/helpers/todo_lists_helper.rb
module TodoListsHelper
end

app/views/home/wellcome.html.erb
<div class="container">
	<div class="jumbotron">
	      <div class="container">
	        <h1>Hello there!</h1>
	        <p>Introducing a brand new way to take care your tasks and discover productivity.</p>
	        <%= link_to "Sign up »",new_user_registration_path, class: "btn btn-custom btn-lg"%>
	        <span class="span-or">or</span>
	        <%= link_to "Sign in with Twitter", user_omniauth_authorize_path(:twitter), class: "btn btn-custom btn-lg" %>
	      </div>
	</div>
</div>
   

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Todo2</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
</head>
<body>
<div class="container">

<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">
  <ul class="nav navbar-nav">
    <li class="active"><%= link_to 'Home', root_path%></li>
  <% if user_signed_in? %>
      <li ><%= current_user.name%></li>
      <li ><%= link_to "Sign out", destroy_user_session_path,:method => :delete %></li>
    <% else %>
      <li ><%= link_to "Sign up", new_user_registration_path %></li>
      <li ><%= link_to "Sign in", new_user_session_path %></li>
      <li ><%= link_to "Sign in with Twitter", user_omniauth_authorize_path(:twitter) %></li>
  <% end %>
  </ul>
  </div>
</nav>  

<div class="row">
  <div class="columns large-12"></div>
  <% flash.each do |type, message| %>
  <div class="container">
    <div class="span4">
      <div data-alert class="alert <%= flash_class(type) %>">
        <%= message %>
        <button type="button" class="close" data-dismiss="alert">×</button>
      </div>
    <% end %>
    </div>
  </div>

  <%= yield %>
</div>

</div>
</body>
</html>

app/views/todo_items/_form.html.erb
<%= form_for ([@todo_list, @todo_list.todo_items.build]),html: { class: "form-inline", role: "form" } do |f| %>
	<div class="form-group">
		<%= f.text_field :title, placeholder: "New Item", class: "form-control" %>
	</div>
	<div class="form-group">
		<div class="form-group">
			<label class="checkbox-inline">
			<%= f.check_box :custom%> Do you want to use a custom time?
			</label>
		</div>

		<div class='input-group date' id='stop'>
			<%= f.time_select :total_time, include_seconds: true%>
		</div>
		<%= f.submit%>
	</div>
<% end %>

app/views/todo_items/_todo_item.html.erb
<% if todo_item.completed? %> 
	<div class="list-group-item">
		<div class="item row">
            <div class="col-xs-5">
				<p style="opacity: 0.6;">
					<strike><%= todo_item.title %></strike>
				</p>
			</div>
			<div class="col-xs-4">
				<% @complete_time = todo_item.completed_at%>
				<% @created_time = todo_item.created_at%>
				<%# @diff_hours = ((@complete_time - @created_time) / 1.hour).round%>
				<% @hours = TimeDifference.between(@complete_time, @created_time).in_hours.to_i %>
				<% @minutes = TimeDifference.between(@complete_time, @created_time).in_minutes.to_i %>
				<% @seconds = TimeDifference.between(@complete_time, @created_time).in_seconds.to_i.round %>
				<% @spent_time = [@hours, @minutes, @seconds].join(':')%>	
				<p> You spent <%=@spent_time%></p>
			</div>
			<div class="col-xs-3">
				<%= link_to todo_list_todo_item_path(@todo_list, todo_item.id), method: :delete, data: { confirm: "Are you sure?" }, class: "pull-right" do%>
				<i class="fa fa-trash"></i>
				<% end %>
			</div>	
		</div>		
	</div>

	<% else %>
	
	<div class="list-group-item">
		<div class="item row">
            <div class="col-xs-4">
				<%= todo_item.title %>
			</div>
			<% if todo_item.custom == false%>
				<div class="col-xs-4">
					<%= todo_item.total_time.strftime("Your custom time %H:%M:%S")%>
				</div>
			<% else %>	
				<div class="col-sm-4">
					<div id="cronometro" class="botonReiniciar"></div>
				</div>	
			<% end %>
			<div class="col-xs-3">
				<%= link_to todo_list_todo_item_path(@todo_list, todo_item.id), method: :delete, data: { confirm: "Are you sure?" }, class: "pull-right" do%>
					<i class="fa fa-trash"></i>
				<% end %>

				<%= link_to complete_todo_list_todo_item_path(@todo_list, todo_item.id), method: :patch, class: "pull-right" do%>
					<i class="fa fa-check"></i>
				<% end %>
			</div>
		</div>
	</div>

<% end %>


<script>
//Muestra el cronometro

var inicioConteo,
idTimeout,
cronometro = document.querySelector("#cronometro"),
botonReiniciar = document.querySelector(".botonReiniciar");

function zeroIzq(n){
return n.toString().replace(/^(d)$/,"0$1");
}

function formatoSegundos(s){
return zeroIzq(Math.floor(s / 3600))+":"+zeroIzq(Math.floor(s%3600 / 60))+":"+zeroIzq(Math.floor((s%3600)%60));
}

function actualizar(){
var dif = Date.now() - inicioConteo;
dif = Math.round(dif / 1000);
cronometro.innerHTML = formatoSegundos(dif);
idTimeout = setTimeout(actualizar,1000);
}

function iniciar(){
clearTimeout(idTimeout);
inicioConteo = Date.now();
actualizar();
}

//botonReiniciar.onclick = function(){
//iniciar();
//}

iniciar();
</script>

app/views/todo_lists/_form.html.erb
<%= form_for(@todo_list) do |f| %>
  <% if @todo_list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@todo_list.errors.count, "error") %> prohibited this todo_list from being saved:</h2>

      <ul>
      <% @todo_list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/todo_lists/edit.html.erb
<h1>Editing Todo List</h1>

<%= render 'form' %>

<%= link_to 'Show', @todo_list %> |
<%= link_to 'Back', todo_lists_path %>

app/views/todo_lists/index.html.erb
<div class="row">
    <div class="col-md-12 text-center"><h1>Listing Todo Lists</h1></div>
        <div class="col-sm-8 col-sm-offset-2">
            <div class="list-group" id="list1">
                <% if @todo_lists.count > 0%>
                <div class="list-group-item">

                    <% @todo_lists.each do |todo_list| %>
                        <div class="list-group-item ">
                            <div class="item row">
                                <div class="col-xs-3">
                                    <h4><%=link_to todo_list.title, todo_list %></h4>
                                </div>
                                <div class="col-xs-5">
                                    <p><%=todo_list.description%></p>
                                </div>
                                <div class="col-xs-2">
                                    <p class="pubdate"><%= time_ago_in_words(todo_list.created_at)%></p>
                                </div>
                                <%= link_to edit_todo_list_path(todo_list), class: 'btn btn-default' do%>
                                    <i class="fa fa-pencil"></i>
                                <% end %>
                                <%= link_to todo_list, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-default' do%>
                                    <i class='fa fa-trash'></i>
                                <% end %> 
                            </div>
                        </div>
                    <% end %>
                    <%= link_to 'New Todo list', new_todo_list_path, class: 'btn btn-default' %>
                </div>
                <% else %>
                <div class="jumbotron" >
                    <h2>
                        Hi there!, it's time to start being productive!
                        <p>
                            Lets get started creating a new project.
                        </p>
                        <p>
                        <%= link_to new_todo_list_path, class: 'btn btn-default' do%>
                            <i class="fa fa-plus-square-o">  New Todo list</i>
                            <% end %> 
                        </p>       
                    </h2>
                    <p class="help">
                        Time reading losing time, rather than working. 
                        <i class="fa fa-clock-o"></i>
                    </p>
                    <div id="cronometro" class="botonReiniciar"></div>
                </div>
                <% end %>
            </div>
        </div>
    </div>
</div>

<script>
//Muestra el cronometro

var inicioConteo,
idTimeout,
cronometro = document.querySelector("#cronometro"),
botonReiniciar = document.querySelector(".botonReiniciar");

function zeroIzq(n){
return n.toString().replace(/^(d)$/,"0$1");
}

function formatoSegundos(s){
return zeroIzq(Math.floor(s / 3600))+":"+zeroIzq(Math.floor(s%3600 / 60))+":"+zeroIzq(Math.floor((s%3600)%60));
}

function actualizar(){
var dif = Date.now() - inicioConteo;
dif = Math.round(dif / 1000);
cronometro.innerHTML = formatoSegundos(dif);
idTimeout = setTimeout(actualizar,1000);
}

function iniciar(){
clearTimeout(idTimeout);
inicioConteo = Date.now();
actualizar();
}

//botonReiniciar.onclick = function(){
//iniciar();
//}

iniciar();
</script>

app/views/todo_lists/new.html.erb
<div class="panel panel-default">
	<div class="panel-heading">
		<div class="container">
			<h1>New Todo List</h1>

			<%= render 'form' %>

			<%= link_to 'Back', todo_lists_path %>
		</div>
	</div>
</div>	

app/views/todo_lists/show.html.erb
<div class="container">
    <div class="row">
        <div class="col-md-12 text-center">
        	<h1><%= link_to "Task lists", todo_lists_path%></h1>
        	<h2>You have <%= pluralize(@todo_list.todo_items.count, "item")%></h2>
        </div>

        <div class="col-md-12 col-sm-12">
        	<div class="list-group">

				<% @todo_lists.each do |list|%>
					<div class="list-group-item active">
					    <div class="item row">
				    	    <div class="col-xs-3">
				        	    <h3 class="source"><%=link_to list.title, edit_todo_list_path(@todo_list)%></h3>
				        	    <i class="fa fa-chevron-down"></i>
				            </div>
				            <div class="col-xs-7">
				            	<p class="help-block"><%= list.description %></p>
				            </div>
				            <div class="col-xs-2">
				            	<p class="pubdate pull-rigth"><%= time_ago_in_words(list.created_at)%></p>
				            </div>
				        </div>
					</div>

					<div class="description row">
			        	<div class="col-md-6">&nbsp;</div>
			        		<div class="col-xs-12">	
								<div class="list-group-item">
									<%= render list.todo_items %>
									<div class="form-group">
										<%= render 'todo_items/form' %>
									</div>
								</div>
							</div>
						</div>
					</div>			
				<% end %>
				
			</div>
		</div>

	</div>
</div>			